Add tests for qemu-tvg backend
astro/microvm.nix pull request #179
Opened 2024-01-04 19:52 UTC by ereslibre

This adds tests for the qemu-tvg backend that check that the emulated machine has the expected architecture. This check also works for the rest of the rest of the hypervisors.

**However**, there is something fishy when running this test case. Please, check the first comment on this PR for the error.

If you have any idea how to tackle this issue I would be glad to update the PR. Thanks!

2024-01-04 20:00 UTC, ereslibre commented
Although I think this PR should work and pass, I'm getting what I think might be unrelated errors. Any help or pointer would be greatly appreciated.

<details>

<summary>Error details</summary>

```
❯ nix build --verbose -L .#hydraJobs.x86_64-linux.qemu-tcg-startup-shutdown
Using saved setting for 'extra-substituters = https://microvm.cachix.org' from ~/.local/share/nix/trusted-settings.json.
Using saved setting for 'extra-trusted-public-keys = microvm.cachix.org-1:oXnBc6hRE3eX5rSYdRyMYXnfzcCxC7yKPTbZXALsqys=' from ~/.local/share/nix/trusted-settings.json.
warning: ignoring untrusted substituter 'https://microvm.cachix.org', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
this derivation will be built:
  /nix/store/90llckn2x023wqh2cr3j3gxgjmyisivw-microvm-test-startup-shutdown.drv
building '/nix/store/90llckn2x023wqh2cr3j3gxgjmyisivw-microvm-test-startup-shutdown.drv'...
microvm-test-startup-shutdown> chattr: Operation not supported while setting flags on var.img
microvm-test-startup-shutdown> mke2fs 1.47.0 (5-Feb-2023)
microvm-test-startup-shutdown> Discarding device blocks: done
microvm-test-startup-shutdown> Creating filesystem with 32768 1k blocks and 8192 inodes
microvm-test-startup-shutdown> Filesystem UUID: 64e2c280-e8df-4f7e-a87d-1791c42385a4
microvm-test-startup-shutdown> Superblock backups stored on blocks:
microvm-test-startup-shutdown>  8193, 24577
microvm-test-startup-shutdown> Allocating group tables: done
microvm-test-startup-shutdown> Writing inode tables: done
microvm-test-startup-shutdown> Creating journal (4096 blocks): done
microvm-test-startup-shutdown> Writing superblocks and filesystem accounting information: done
microvm-test-startup-shutdown> <<< NixOS Stage 1 >>>
microvm-test-startup-shutdown> loading module virtio_mmio...
microvm-test-startup-shutdown> loading module virtio_pci...
microvm-test-startup-shutdown> loading module virtio_blk...
microvm-test-startup-shutdown> loading module 9pnet_virtio...
microvm-test-startup-shutdown> loading module 9p...
microvm-test-startup-shutdown> loading module virtiofs...
microvm-test-startup-shutdown> loading module dm_mod...
microvm-test-startup-shutdown> running udev...
microvm-test-startup-shutdown> Starting systemd-udevd version 254.6
microvm-test-startup-shutdown> kbd_mode: KDSKBMODE: Inappropriate ioctl for device
microvm-test-startup-shutdown> %Gstarting device mapper and LVM...
microvm-test-startup-shutdown> mounting rootfs on /...
microvm-test-startup-shutdown> mounting /dev/disk/by-label/nix-store on /nix/store...
microvm-test-startup-shutdown> [    4.947356] /dev/disk/by-label/nix-store: Can't open blockdev
microvm-test-startup-shutdown> checking /dev/vdb...
microvm-test-startup-shutdown> fsck (busybox 1.36.1)
microvm-test-startup-shutdown> [fsck.ext4 (1) -- /mnt-root/var] fsck.ext4 -a /dev/vdb
microvm-test-startup-shutdown> /dev/vdb is mounted.
microvm-test-startup-shutdown> e2fsck: Cannot continue, aborting.
microvm-test-startup-shutdown> fsck on /dev/vdb failed.
microvm-test-startup-shutdown> An error occurred in stage 1 of the boot process, which must mount the
microvm-test-startup-shutdown> root filesystem on `/mnt-root' and then start stage 2.  Press one
microvm-test-startup-shutdown> of the following keys:
microvm-test-startup-shutdown>   r) to reboot immediately
microvm-test-startup-shutdown>   *) to ignore the error and continue
[1/0/1 built] building microvm-test-startup-shutdown
```
</details>

Trying to change the mountpoint from `/var` to `/var/.output` on [`startup-shutdown.nix`](https://github.com/astro/microvm.nix/blob/d5553b1388f2947915c4cec6249b89474046573a/checks/startup-shutdown.nix#L18) gets a little further (!! -- no clue why, diff on top of this PR), but still doesn't work:

<details>

<summary>Error details</summary>

```
❯ nix build --verbose -L .#hydraJobs.x86_64-linux.qemu-tcg-startup-shutdown
warning: Git tree '/home/ereslibre/projects/astro/microvm.nix' is dirty
Using saved setting for 'extra-substituters = https://microvm.cachix.org' from ~/.local/share/nix/trusted-settings.json.
Using saved setting for 'extra-trusted-public-keys = microvm.cachix.org-1:oXnBc6hRE3eX5rSYdRyMYXnfzcCxC7yKPTbZXALsqys=' from ~/.local/share/nix/trusted-settings.json.
warning: ignoring untrusted substituter 'https://microvm.cachix.org', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
this derivation will be built:
  /nix/store/zka9lz2sdansmf7rcrdz5nd7k46ghmjg-microvm-test-startup-shutdown.drv
building '/nix/store/zka9lz2sdansmf7rcrdz5nd7k46ghmjg-microvm-test-startup-shutdown.drv'...
microvm-test-startup-shutdown> chattr: Operation not supported while setting flags on var.img
microvm-test-startup-shutdown> mke2fs 1.47.0 (5-Feb-2023)
microvm-test-startup-shutdown> Discarding device blocks: done
microvm-test-startup-shutdown> Creating filesystem with 32768 1k blocks and 8192 inodes
microvm-test-startup-shutdown> Filesystem UUID: f6e8c29b-d0fa-4f8c-a58a-f91323b7967c
microvm-test-startup-shutdown> Superblock backups stored on blocks:
microvm-test-startup-shutdown>  8193, 24577
microvm-test-startup-shutdown> Allocating group tables: done
microvm-test-startup-shutdown> Writing inode tables: done
microvm-test-startup-shutdown> Creating journal (4096 blocks): done
microvm-test-startup-shutdown> Writing superblocks and filesystem accounting information: done
microvm-test-startup-shutdown> <<< NixOS Stage 1 >>>
microvm-test-startup-shutdown> loading module virtio_mmio...
microvm-test-startup-shutdown> loading module virtio_pci...
microvm-test-startup-shutdown> loading module virtio_blk...
microvm-test-startup-shutdown> loading module 9pnet_virtio...
microvm-test-startup-shutdown> loading module 9p...
microvm-test-startup-shutdown> loading module virtiofs...
microvm-test-startup-shutdown> loading module dm_mod...
microvm-test-startup-shutdown> running udev...
microvm-test-startup-shutdown> Starting systemd-udevd version 254.6
microvm-test-startup-shutdown> kbd_mode: KDSKBMODE: Inappropriate ioctl for device
microvm-test-startup-shutdown> %Gstarting device mapper and LVM...
microvm-test-startup-shutdown> mounting rootfs on /...
microvm-test-startup-shutdown> mounting /dev/disk/by-label/nix-store on /nix/store...
microvm-test-startup-shutdown> [    4.945547] /dev/disk/by-label/nix-store: Can't open blockdev
microvm-test-startup-shutdown> <<< NixOS Stage 2 >>>
microvm-test-startup-shutdown> running activation script...
microvm-test-startup-shutdown> setting up /etc...
microvm-test-startup-shutdown> error: creating directory '/nix/store/.links': Read-only file system
microvm-test-startup-shutdown> starting systemd...
microvm-test-startup-shutdown> Welcome to NixOS 24.05 (Uakari)!
microvm-test-startup-shutdown> [  OK  ] Created slice Slice /system/getty.
microvm-test-startup-shutdown> [  OK  ] Created slice Slice /system/modprobe.
microvm-test-startup-shutdown> [  OK  ] Created slice Slice /system/serial-getty.
microvm-test-startup-shutdown> [  OK  ] Created slice Slice /system/systemd-fsck.
microvm-test-startup-shutdown> [  OK  ] Created slice User and Session Slice.
microvm-test-startup-shutdown> [  OK  ] Started Dispatch Password Requests to Console Directory Watch.
microvm-test-startup-shutdown> [  OK  ] Started Forward Password Requests to Wall Directory Watch.
microvm-test-startup-shutdown> [  OK  ] Reached target Local Encrypted Volumes.
microvm-test-startup-shutdown> [  OK  ] Reached target Containers.
microvm-test-startup-shutdown> [  OK  ] Reached target Path Units.
microvm-test-startup-shutdown> [  OK  ] Reached target Remote File Systems.
microvm-test-startup-shutdown> [  OK  ] Reached target Slice Units.
microvm-test-startup-shutdown> [  OK  ] Reached target Swaps.
microvm-test-startup-shutdown> [  OK  ] Listening on Process Core Dump Socket.
microvm-test-startup-shutdown> [  OK  ] Listening on Journal Socket (/dev/log).
microvm-test-startup-shutd [...]

2024-01-07 09:38 UTC, ereslibre commented
I think this might be related to the [`virt` generic virtual platform default behavior of producing a DTB](https://qemu-project.gitlab.io/qemu/system/arm/virt.html#hardware-configuration-information-for-bare-metal-programming), and the kernel loading it, what is different than the regular run with the `microvm` virtual platform, [that does not do any of this](https://www.qemu.org/docs/master/system/i386/microvm.html).

I will continue checking to see if we can have a similar behavior with the `virt` virtual platform.

2024-01-12 12:57 UTC, ereslibre commented on lib/default.nix
> +        mkfs.${fsType} ${pkgs.lib.optionalString (label != null) "-L '${label}'"} '${image}'
Different `fsTypes` might have different arguments for labeling volumes. Should I make this parametric at least for the most common ones? WDYT?

E.g. `mkfs.ext4` has `-L` whereas `mkfs.vfat` has `-n`.

2024-01-12 13:00 UTC, ereslibre commented
This is working as expected now. Under the `virt` generic virtual platform, the nix store is for some reason under `/dev/vdb` whereas under the `microvm` generic virtual platform, it is under `/dev/vda`. This makes the identification of storage devices brittle when using their letter identifiers.

For this reason, a new optional "label" attribute is added to volumes, only applicable when `autoCreate` is provided. If this attribute is provided, the volume will be identified by `/dev/disk/by-label` instead of `/dev/vdN`.

2024-01-12 21:57 UTC, astro requested changes
I considered mounting volumes by label before but it had be optional because sometimes you just can't rely on those labels. Now I see that it doesn't inflate the code too much, and that makes me very happy.

Many thanks for the additional test! Did you see the `ci` branch I am currently working on?

2024-01-12 21:57 UTC, astro commented on lib/default.nix
> +        mkfs.${fsType} ${pkgs.lib.optionalString (label != null) "-L '${label}'"} '${image}'
Yes, please do so. I would like to have at least ext[234], xfs, and vfat.

2024-01-13 12:05 UTC, ereslibre commented on lib/default.nix
> +        mkfs.${fsType} ${pkgs.lib.optionalString (label != null) "-L '${label}'"} '${image}'
Done :)

2024-01-13 12:06 UTC, ereslibre commented
> I considered mounting volumes by label before but it had be optional because sometimes you just can't rely on those labels. Now I see that it doesn't inflate the code too much, and that makes me very happy.

Super :)

> Many thanks for the additional test! Did you see the ci branch I am currently working on?

I didn't realize! Let  me know if you prefer to wait for this to merge, or if you want me to do some changes on this PR related to that ongoing work.

Thanks a lot for the review!

2024-01-14 20:11 UTC, merged

2024-01-17 01:24 UTC, astro commented
Sorry, this test can't run in a Github free tier CI pipeline because it compiles for too long. I'd like to wait for ideas instead of throwing money at it. :-)

2024-01-17 08:39 UTC, ereslibre commented
> Sorry, this test can't run in a Github free tier CI pipeline because it compiles for too long. I'd like to wait for ideas instead of throwing money at it. :-)

I can look into what makes the compilation slow. I have this on my machine as well, given there's something that needs to be cross-compiled and is not in the NixOS cache. I believe this is the main issue.

This is not yet running, right? Where is this being built on CI as of today?

I think it would make sense to have a "slow tests" attribute or something like that, that is only evaluated from time to time, and not on every single PR or commit. I would be fine to take care of those issues and bisect myself to find the culprit of the non-passing test. These tests could also be non-blocking for a new "release" if you will and if you are fine with it.