Fix tapScript doc rendering
astro/microvm.nix pull request #288
Opened 2024-10-19 15:34 UTC by SuperSandro2000

see https://search.nixos.c3d2.de/?scope=6&option=microvm.host.tapScript

2024-10-19 15:39 UTC, SuperSandro2000 commented on nixos-modules/host/options.nix
> +      defaulText = "''${pkgs.iproute2}/bin/ip link set "$id" up";
```suggestion
      defaultText = "''${pkgs.iproute2}/bin/ip link set "$id" up";
```

2024-10-19 19:12 UTC, astro requested changes
Why did this PR have draft status?

2024-10-19 19:15 UTC, SuperSandro2000 commented on nixos-modules/host/options.nix
> +      defaultText = "''${pkgs.iproute2}/bin/ip link set "$id" up";
```suggestion
      defaultText = "''${pkgs.iproute2}/bin/ip link set \"$id\" up";
```

2024-10-19 19:15 UTC, SuperSandro2000 commented
> Why did this PR have draft status?

@codingmarcel is supposed to look, if it is now what we expect

2024-10-20 10:43 UTC, MarcelCoding commented on nixos-modules/host/options.nix
> +      default = "${pkgs.iproute2}/bin/ip link set "$id" up";
```suggestion
      default = "${pkgs.iproute2}/bin/ip link set \"$id\" up";
```

2024-10-21 21:33 UTC, astro requested changes

2024-10-21 21:33 UTC, astro commented on nixos-modules/host/options.nix
> +      default = "${pkgs.iproute2}/bin/ip link set \"$id\" up";
Can we keep the `default = ''` with a newline, now that we have the `defaultText` too?

2024-10-22 18:14 UTC, merged