make modules opt-out after import
astro/microvm.nix pull request #62
Opened 2022-11-03 11:47 UTC by nazarewk

fixes https://github.com/astro/microvm.nix/issues/61

2022-11-03 12:29 UTC, nazarewk commented
this is not side-effect-free, but good enough (only enables imported minimal profile).

2022-11-03 15:24 UTC, astro requested changes
Thank you. This looks good to me except for the indentation.

May I ask about the use-case for this change? I want to avoid breaking it in the future.

2022-11-03 15:24 UTC, astro commented on nixos-modules/microvm/stage-1.nix
> +};
Lines in between these curly braces need to be indented.

2022-11-03 15:24 UTC, astro commented on nixos-modules/microvm/system.nix
> +};
Likewise

2022-11-07 09:58 UTC, nazarewk commented
I thought about formatting it with `nixpkgs-fmt`, but it made MANY changes.

About my use case: I have a [repo holding all my configs in opt-in modules](https://github.com/nazarewk-iac/nix-configs), so i can pick only relevant pieces for different configs/machines. It works fine except for things using "plain" configs not hidden behind (eg: [this importing qemu guest from nixpkgs](https://github.com/nazarewk-iac/nix-configs/blob/b8f5532608650f57f1f14ecd05a0e9b07887d088/machines/hetzner/wg-0/default.nix#L2-L6))

2022-11-09 19:11 UTC, astro commented
git's word-diff didn't work well for me regardless of the chosen algorithm. Therefore I indented myself.

Thank you!

2022-11-09 19:11 UTC, closed without merging